---
- name: Install alacritty
  become: true
  ansible.builtin.package:
    name: alacritty
    state: present

- name: Copy alacritty config
  ansible.builtin.copy:
    src: /tmp/dotfiles/alacritty
    dest: ~/.config/
    remote_src: true
