---
- name: Configure host when Fedora
  become: true
  block:
    - name: Tune DNF
      lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: "^{{ item.param }}"
        line: "{{ item.param }}={{ item.value }}"
      loop:
        - param: fastestmirror
          value: True
        - param: max_parallel_downloads
          value: 8
        - param: minrate
          value: 10M

    - name: Update packages
      yum:
        name: "*"
        state: latest

    # FIXME: Changed to shell because current ansible
    # contains a bug https://github.com/ansible/ansible/issues/85124
    - name: Install rpmfusion
      when: enable_rpmfusion
      become: true
      ansible.builtin.shell: >
        dnf install -y
        https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
        https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm

    - name: Install basic packages
      yum:
        name: "{{ common_packages }}"
        state: latest
      when: common_packages

    - name: Install KDE packages
      yum:
        name: "{{ kde_packages }}"
        state: latest
      when: kde_packages and desktop_env == 'kde'

    - name: Install GNOME packages
      yum:
        name: "{{ gnome_packages }}"
        state: latest
      when: gnome_packages and desktop_env == 'gnome'

    - name: Install dev packages
      yum:
        name: "{{ dev_packages }}"
        state: latest
      when: dev_packages

    - name: Remove packages
      yum:
        name: "{{ remove_packages }}"
        state: absent
      when: remove_packages

    - name: Install npm packages
      shell: "npm install -g {{ npm_packages | join(' ') }}"
      when: npm_packages

  when: ansible_distribution == 'Fedora'

- name: Install pip packages in user space
  ansible.builtin.pip:
    name: "{{ pip_packages }}"
    state: forcereinstall
    extra_args: --user
  when: pip_packages
