---
- name: Clone doom emacs
  git:
    repo: https://github.com/hlissner/doom-emacs
    dest: ~/.emacs.d
    depth: 1

- name: Install emacs
  become: true
  yum:
    name: emacs
    state: present

- name: Install doom emacs
  shell: |
    ~/.emacs.d/bin/doom -y install
  args:
    chdir: ~/.emacs.d
