---
- name: Clone doom emacs
  ansible.builtin.git:
    repo: https://github.com/hlissner/doom-emacs
    dest: ~/.emacs.d

- name: Install emacs
  become: true
  ansible.builtin.package:
    name: emacs
    state: present

- name: Install doom emacs
  ansible.builtin.shell: |
     ~/.emacs.d/bin/doom install --install --fonts --force
  args:
    chdir: ~/.emacs.d
  changed_when: true
