---
- name: Clone doom emacs
  git:
    repo: https://github.com/hlissner/doom-emacs
    dest: ~/.emacs.d

- name: Install emacs
  become: true
  yum:
    name: emacs
    state: present

- name: Install doom emacs
  shell: |
     ~/.emacs.d/bin/doom install --install --fonts --force
  args:
    chdir: ~/.emacs.d
