---
- name: Enable flathub
  become: true
  shell: |
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak packages
  shell: |
    flatpak install -y {{ item }}
  loop: "{{ flatpak_packages }}"
