---
- name: Enable flathub
  become: true
  ansible.builtin.shell: |
    flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak packages
  ansible.builtin.shell: |
    flatpak install --user -y {{ item }}
  loop: "{{ flatpak_packages }}"
