---
- name: Clone fzf repo
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf
    dest: ~/.fzf
    update: true

- name: Setup fzf
  ansible.builtin.shell: |
    ~/.fzf/install --all
  changed_when: true
