---
- name: Setup Kubernetes tools
  block:
    - name: Configure repository
      become: true
      copy:
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
          enabled=1
          gpgcheck=1
          gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        dest: /etc/yum.repos.d/kubernetes.repo

    - name: Install Kubernetes tools
      become: true
      yum:
        name: kubectl
        state: present
  when: enable_kubernetes_tools and ansible_distribution == 'Fedora'
