---
- name: Install required packages
  become: true
  ansible.builtin.package:
    name: cargo
    state: present

- name: Install lunar vim - nightly version
  ansible.builtin.shell: |
    bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh) -y
