---
- name: Clone dotfiles repo
  ansible.builtin.include_tasks: repo.yml

- name: Install common packages
  ansible.builtin.include_tasks: common.yml
  when: "'common' in components"

- name: Configure ansible
  ansible.builtin.include_tasks: ansible.yml
  when: "'ansible' in components"

- name: Install nerd fonts
  ansible.builtin.include_tasks: nerdfonts.yml
  when: "'nerdfonts' in components"

- name: Configure nodejs
  ansible.builtin.include_tasks: nodejs.yml
  when: "'nodejs' in components"

- name: Configure vim
  ansible.builtin.include_tasks: vim.yml
  when: "'vim' in components"

- name: Configure lunarvim
  ansible.builtin.include_tasks: lvim.yml
  when: "'lvim' in components"

- name: Configure zsh
  ansible.builtin.include_tasks: zsh.yml
  when: "'zsh' in components"

- name: Configure tmux
  ansible.builtin.include_tasks: tmux.yml
  when: "'tmux' in components"

- name: Configure adb
  ansible.builtin.include_tasks: adb.yml
  when: "'adb' in components"

- name: Configure emacs
  ansible.builtin.include_tasks: emacs.yml
  when: "'emacs' in components"

- name: Configure fzf
  ansible.builtin.include_tasks: fzf.yml
  when: "'fzf' in components"

- name: Configure alacritty
  ansible.builtin.include_tasks: alacritty.yml
  when: "'alacritty' in components"

- name: Configure git
  ansible.builtin.include_tasks: git.yml
  when: "'git' in components"

- name: Configure system
  ansible.builtin.include_tasks: system.yml
  when: "'system' in components"

- name: Configure Kubernetes packages
  ansible.builtin.include_tasks: kubernetes.yml
  when: "'kubernetes' in components"

- name: Configure flatpak
  ansible.builtin.include_tasks: flatpak.yml
  when: "'flatpak' in components"

- name: Configure Visual Studio Code
  ansible.builtin.include_tasks: visualstudio.yml
  when: "'visualstudio' in components"
