---
- name: Download nvim appimage
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/download/{{ nvim_version }}/nvim.appimage"
    dest: /tmp/nvim.appimage
    mode: '0755'

- name: Extract Neovim appimage
  shell: |
    cd /tmp && ./nvim.appimage --appimage-extract

- name: Create local dir if not exists
  file:
    path: ~/.local/nvim
    state: directory
    recurse: true

- name: Ensure config dir exists
  ansible.builtin.file:
    path: ~/.config/nvim
    state: directory

- name: Ensure old neovim dir does not exists
  ansible.builtin.file:
    path: ~/.local/nvim
    state: absent

- name: Copy extracted neovim
  copy:
    src: /tmp/squashfs-root/
    dest: ~/.local/nvim
    remote_src: true

- name: Ensure userspace local bin exists
  file:
    path: ~/.local/bin
    state: directory

- name: Create symlink neovim to local bin
  file:
    src: ~/.local/nvim/usr/bin/nvim
    dest: ~/.local/bin/nvim
    state: link

- name: Create optional symlink from neovim to vim in userspace bin
  file:
    src: ~/.local/nvim/usr/bin/nvim
    dest: ~/.local/bin/vim
    state: link
