---
- name: Download Neovim appimage
  shell: |
    curl -L "https://github.com/neovim/neovim/releases/download/{{ nvim_version }}/nvim.appimage" -o /tmp/nvim.appimage ;
    cd /tmp/;
    chmod u+x /tmp/nvim.appimage ;
    ./nvim.appimage --appimage-extract

- name: Create local dir if not exists
  file:
    path: ~/.local/nvim
    state: directory
    recurse: true

- name: Copy extracted neovim and make symlink to local bin
  copy:
    src: /tmp/squashfs-root/
    dest: ~/.local/nvim
    remote_src: true

- name: Ensure userspace local bin exists
  file:
    path: ~/.local/bin
    state: directory

- name: Create symlink neovim to local bin
  file:
    src: ~/.local/nvim/usr/bin/nvim
    dest: ~/.local/bin/nvim
    state: link

- name: Create optional symlink from neovim to vim in userspace bin
  file:
    src: ~/.local/nvim/usr/bin/nvim
    dest: ~/.local/bin/vim
    state: link
