---
- name: Check if NodeJS is already available
  environment:
    PATH: ~/.local/bin:/usr/local/bin/:{{ ansible_env.PATH }}
  shell: |
    npm --version
  register: npm_version
  ignore_errors: true

- name: Setup NodeJS
  when: npm_version.rc != 0 or nodejs_userspace
  block:
    - name: Remove old local dirs
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "~/.local/bin"
        - "~/.local/yarn"
        - "~/.local/nodejs"

    - name: Ensure local dir exists
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "~/.local/bin"
        - "~/.local/yarn"
        - "~/.local/nodejs"

    - name: Install xz package
      become: true
      package:
        name: xz
        state: present

    - name: Get latest version
      when: nodejs_version == "latest"
      block:
        - name: Fetch publication page
          get_url:
            url: https://nodejs.org/dist/latest/
            dest: /tmp/nodejs-latest

        - name: Get version
          shell: |
            sed -r 's/^.*href="([^"]+)".*/\1/' /tmp/nodejs-latest | grep linux-x64.tar.gz | cut -f2 -d'-'
          register: latest_nodejs_version

    - name: "Download and unpack nodejs version {{ latest_nodejs_version.stdout | default(nodejs_version) }}"
      ansible.builtin.unarchive:
        src: "https://nodejs.org/dist/{{ latest_nodejs_version.stdout | default(nodejs_version) }}/node-{{ latest_nodejs_version.stdout | default(nodejs_version) }}-linux-x64.tar.xz"
        dest: ~/.local/nodejs
        remote_src: true
        extra_opts: [--strip-components=1]

    - name: Download and unpack yarn
      ansible.builtin.unarchive:
        src: "https://yarnpkg.com/latest.tar.gz"
        dest: ~/.local/yarn
        remote_src: true
        extra_opts: [--strip-components=1]

    - name: Create symlinks
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop:
        - src: "~/.local/nodejs/bin/npm"
          dest: "~/.local/bin/npm"
        - src: "~/.local/nodejs/bin/node"
          dest: "~/.local/bin/node"
        - src: "~/.local/yarn/bin/yarn"
          dest: "~/.local/bin/yarn"

- name: Install nodejs package
  when: npm_version.rc != 0 and not nodejs_userspace
  block:
    - name: Configure NodeJS repo - Centos 7
      become: true
      shell: |
        curl --silent --location https://rpm.nodesource.com/setup_14.x | bash
      when: ansible_distribution == 'CentOS' and ansible_lsb.major_release|int <= 7

    - name: Install NodeJS
      become: true
      package:
        name: nodejs
        state: present
