---
- name: Disable Wireless powersave
  become: true
  block:
    - name: Create NetworkManager conf.d dir
      file:
        path: /etc/NetworkManager/conf.d
        state: directory

    - name: Disable power save for Wireless device
      copy:
        content: |
          [connection]
          wifi.powersave = 2
        dest: /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf
      register: wifi_powersave
      when: wifi_disable_powersave

    ## https://wiki.archlinux.org/title/NetworkManager#DHCP_client
    #    - name: Change default dhcp client when issue with OpenWRT and VPN
    #      copy:
    #        content: |
    #          [main]
    #          dhcp=dhclient
    #          # dhcp=dhcpcd
    #          # dhcp=internal
    #        dest: /etc/NetworkManager/conf.d/00-dhcp-client.conf

    #    ## Try to fix error:
    #    # Using degraded feature set UDP instead of UDP+EDNS0 for DNS server 192.168.88.1,
    #    # where 192.168.88.1 is an router base on OpenWRT.
    #    # By default, the DNS cache is enabled on the router, so it might
    #    # be problematic when local connection + VPN + Virtual interfaces + etc.
    #    # is configured.
    #    # https://superuser.com/questions/1676584/using-degraded-feature-set-tcp-instead-of-udp-for-dns-server
    #    - name: Disable DNSSec
    #      become: true
    #      lineinfile:
    #        path: /etc/systemd/resolved.conf
    #        regexp: '^DNSSEC='
    #        line: 'DNSSEC=no'

    - name: Disable systemd-resolved
      become: true
      service:
        name: systemd-resolved
        state: stopped
        enabled: false
      register: _disable_resolved

    - name: Set dns to default in Network Manger
      become: true
      ini_file:
        path: /etc/NetworkManager/NetworkManager.conf
        section: main
        option: dns
        value: default
        no_extra_spaces: true

    - name: Clear resolv.conf file
      become: true
      file:
        path: /etc/resolv.conf
        state: absent
      when: _disable_resolved.changed

    - name: Restart NetworkManager
      become: true
      service:
        name: NetworkManager
        state: restarted
      when: _disable_resolved.changed or wifi_powersave is defined and wifi_powersave.changed
      register: _nm_restarted

    - name: Wait few seconds before continue
      ansible.builtin.pause:
        seconds: 30
      when: _nm_restarted.changed

- name: Configure powertop service
  become: true
  block:
    - name: Create service file
      copy:
        content: |
          [Unit]
          Description=PowerTOP auto tune

          [Service]
          Type=oneshot
          Environment="TERM=dumb"
          RemainAfterExit=true
          ExecStart=/usr/sbin/powertop --auto-tune

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/powertop.service

    - name: Enable powertop service
      service:
        name: powertop
        state: started
        enabled: true
        daemon-reload: true

  when: enable_powertop

- name: Enable podman socket
  shell: |
    systemctl --user enable --now podman.socket

- name: Increase map count
  become: true
  sysctl:
    name: vm.max_map_count
    value: "262144"
    state: present
    reload: true

- name: Enable nested virtualization
  include_tasks: nested_virt.yml
  when: enable_nested_virtualization

- name: Add user to libvirt group
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: libvirt
    append: true
