---
- name: Clone tmux package manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    force: true
  ignore_errors: true

- name: Copy tmux config
  copy:
    src: /tmp/dotfiles/tmux/.tmux.conf
    dest: ~/.tmux.conf
    remote_src: true

- name: Configure tmux
  shell: |
    bash ~/.tmux/plugins/tpm/bin/install_plugins
