---
- name: Ensure C compiler is available
  become: true
  ansible.builtin.package:
    name: gcc
    state: present

- name: Copy config
  ansible.builtin.copy:
    src: /tmp/dotfiles/vimrc/kickstart/{{ item }}
    dest: ~/.config/nvim/{{ item }}
    remote_src: true
  loop:
    - init.lua
    - lua/

- name: Overwrite with minimal if set
  when: nvim_minimal
  ansible.builtin.copy:
    src: /tmp/dotfiles/vimrc/kickstart/init-minimal.lua
    dest: ~/.config/nvim/init.lua
    remote_src: true
