---
- name: Copy vim config
  copy:
    src: /tmp/dotfiles/vimrc/init.vim
    dest: ~/.vimrc
    remote_src: true

- name: Ensure directories exists
  file:
    path: ~/.vim/autoload
    state: directory

- name: Download vim plug
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
    mode: "0644"

- name: Create vim directory
  file:
    path: ~/.vim/plugin_conf
    state: directory
    recurse: true

- name: Copy config files
  copy:
    src: "/tmp/dotfiles/vimrc/{{ item }}"
    dest: ~/.vim/
    remote_src: true
  loop:
    - "general.vim"
    - "plugins_conf.vim"
    - "plugins.vim"
    - "lua"

- name: Copy config files
  copy:
    src: "/tmp/dotfiles/vimrc/plugin_conf/{{ item }}"
    dest: "~/.vim/plugin_conf/{{ item }}"
    remote_src: true
  loop:
    - "coc"

- name: Copy vimrc file
  copy:
    src: "/tmp/dotfiles/vimrc/init.vim"
    dest: "~/.vimrc"
    remote_src: true

- name: Ensure directories exists
  file:
    path: ~/.config/nvim/autoload
    state: directory

- name: Do neovim
  when: vim_distro == 'neovim'
  block:
    - name: Download vim plug
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: ~/.config/nvim/autoload/plug.vim
        mode: "0644"

    - name: Setup Neovim
      include_tasks: neovim.yml

    - name: Create symbolic link between vimrc and nvim init
      file:
        src: ~/.vimrc
        dest: ~/.config/nvim/init.vim
        state: link

    - name: Create symlink to lua dir
      ansible.builtin.file:
        src: ~/.vim/lua
        dest: ~/.config/nvim/lua
        state: link
      when: vim_distro == 'neovim'

    - name: Clone nvim-lspconfig
      ansible.builtin.git:
        repo: https://github.com/neovim/nvim-lspconfig
        dest: /tmp/nvim-lspconfig

    - name: Copy lspconfig and lspconfig.lua
      ansible.builtin.copy:
        src: "/tmp/nvim-lspconfig/lua/{{ item.src }}"
        dest: "~/.vim/lua/{{ item.dest }}"
        remote_src: true
      loop:
        - src: lspconfig.lua
          dest: lspconfig.lua
        - src: lspconfig
          dest: lspconfig

- name: Configure vim plugins
  environment:
    PATH: ~/.local/bin:/usr/local/bin/:{{ ansible_env.PATH }}
  block:
    - name: Install vim plugins - vim
      shell: |
        vim +PlugInstall +qall
      when: vim_distro == 'vim'

    - name: Install vim plugins - neovim
      shell: |
        # old way: ~/.local/nvim/usr/bin/nvim +PlugInstall +qall
        ~/.local/nvim/usr/bin/nvim --headless +PlugInstall +qall
      when: vim_distro == 'neovim'

    - name: Install mason packages
      ansible.builtin.shell: |
        ~/.local/nvim/usr/bin/nvim --headless -c "MasonInstall {{ mason_packages | join(' ') }}" -c qall

- name: Install additional packages for vim
  pip:
    name:
      - types-PyYAML
      - types-requests
      - pylama
      - neovim
      - mypy
      - pynvim
      - rstcheck
      - proselint
      - gitlint
      - ansible-lint
      - black
      - yapf
      - vim-vint
      - yamllint
      - jedi
      - pylint
    extra_args: --user
  when: pip_packages

- name: Install additional npm packages
  become: true
  environment:
    PATH: ~/.local/bin:/usr/local/bin/:{{ ansible_env.PATH }}
  shell: |
    npm install -g prettier eslint

- name: Install gopls
  ansible.builtin.shell: |
    go install golang.org/x/tools/gopls@latest

- name: Add PATH to bashrc
  lineinfile:
    path: ~/.bashrc
    regexp: "export PATH"
    line: "export PATH=~/.local/share/nvim/mason/bin/:~/.local/bin:~/go/bin:/usr/local/bin/:{{ ansible_env.PATH }}"
