---
- name: Check if oh my zsh already exists
  stat:
    path: ~/.oh-my-zsh
  register: _omz_status

- name: Configure Oh My ZSH
  shell: |
    curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash
  when: not _omz_status.stat.exists

- name: Copy powerlevel10k config file
  copy:
    src: /tmp/dotfiles/powerlevel10k/.p10k.zsh
    dest: ~/.p10k.zsh
    remote_src: true

- name: Clone powerlevel10k deps
  git:
    repo: https://github.com/romkatv/powerlevel10k
    dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
    depth: 1

- name: Clone autosugestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

- name: Copy zsh config files
  copy:
    src: "/tmp/dotfiles/oh_my_zsh/{{ item }}"
    dest: ~/{{ item }}
    remote_src: true
  loop:
    - ".zsh_ohmyzsh"
    - ".zshrc"

- name: Change user shell to ZSH
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Add PATH to zshrc
  lineinfile:
    path: ~/.zshrc
    regexp: "export PATH"
    line: "export PATH=~/.local/share/nvim/mason/bin/:~/.local/bin:~/go/bin:/usr/local/bin/:{{ ansible_env.PATH }}"
