require'lspconfig'.ansiblels.setup{}
require'lspconfig'.autotools_ls.setup{}
require'lspconfig'.bashls.setup{}
require'lspconfig'.dhall_lsp_server.setup{}
require'lspconfig'.dockerls.setup{}
require'lspconfig'.gopls.setup{}
require'lspconfig'.harper_ls.setup{}
require'lspconfig'.helm_ls.setup{}
require'lspconfig'.html.setup{}
require'lspconfig'.jedi_language_server.setup{}
require'lspconfig'.jinja_lsp.setup{}
require'lspconfig'.jqls.setup{}
require'lspconfig'.jsonls.setup{}
require'lspconfig'.lua_ls.setup{}
require'lspconfig'.marksman.setup{}
require'lspconfig'.pyright.setup{}
require'lspconfig'.pylsp.setup{}
require'lspconfig'.ruff.setup{}
require'lspconfig'.ruff_lsp.setup{}
require'lspconfig'.rust_analyzer.setup{}
require'lspconfig'.vimls.setup{}
require'lspconfig'.yamlls.setup{}
