---
- name: Setup dotfiles
  hosts: localhost
  vars:
    disable_gpg_check: true
    desktop_env: kde
    components:
      - git
      - common
      - ansible
      - nerdfonts
      - nodejs
      - vim
      - emacs
      - tmux
      - alacritty
      - fzf
      - zsh
      - git
      - system
      - kubernetes
      - flatpak
      - visualstudio
  roles:
    - dotfiles
