---
components: []

enable_rpmfusion: true
enable_nerd_fonts: true
enable_kubernetes_tools: true
kubernetes_repo_version: v1.30
enable_nested_virtualization: true

# package, direct or patched
nerd_fonts_install: patched
# small or full
nerd_fonts_pack: small
nerd_fonts_version: v3.3.0
nerd_fonts:
  - RobotoMono
  - DroidSansMono
  - Hack
  - JetBrainsMono
  - FiraCode
  - CascadiaCode

nerd_fonts_package:
  - adobe-source-code-pro-fonts
  - google-roboto-fonts
  - google-roboto-mono-fonts
  - google-droid-sans-fonts
  - google-droid-sans-mono-fonts
  - source-foundry-hack-fonts
  - fira-code-fonts
  - cascadia-code-fonts

nerd_fonts_patched:
  - "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/{{ nerd_fonts_version }}/patched-fonts/RobotoMono/Regular/RobotoMonoNerdFontMono-Regular.ttf"
  - "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/{{ nerd_fonts_version }}/patched-fonts/DroidSansMono/DroidSansMNerdFontMono-Regular.otf"
  - "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/{{ nerd_fonts_version }}/patched-fonts/Hack/Regular/HackNerdFontMono-Regular.ttf"
  - "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/{{ nerd_fonts_version }}/patched-fonts/JetBrainsMono/NoLigatures/Regular/JetBrainsMonoNLNerdFontMono-Regular.ttf"
  - "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/{{ nerd_fonts_version }}/patched-fonts/FiraCode/Regular/FiraCodeNerdFontMono-Regular.ttf"
  - "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/{{ nerd_fonts_version }}/patched-fonts/CascadiaCode/Regular/CaskaydiaCoveNerdFontMono-Regular.ttf"

other_fonts:
  - "https://raw.githubusercontent.com/githubnext/monaspace/main/fonts/otf/MonaspaceArgon-Regular.otf"
  - "https://raw.githubusercontent.com/githubnext/monaspace/main/fonts/otf/MonaspaceKrypton-Regular.otf"
  - "https://raw.githubusercontent.com/githubnext/monaspace/main/fonts/otf/MonaspaceNeon-Regular.otf"
  - "https://raw.githubusercontent.com/githubnext/monaspace/main/fonts/otf/MonaspaceRadon-Regular.otf"
  - "https://raw.githubusercontent.com/githubnext/monaspace/main/fonts/otf/MonaspaceXenon-Regular.otf"

# available: prezto, starship, oh_my_zsh
zsh_distro: oh_my_zsh
nvim_version: nightly
nvim_use_coc: false

# it install nodejs into ~/.local/nodejs
# https://nodejs.org/dist/latest-v20.x/
nodejs_userspace: true
nodejs_version: latest

wifi_disable_powersave: true
disable_systemd_resolved: true
nm_dns_workaround: true
enable_powertop: false

common_packages:
  - alacritty
  - android-file-transfer
  - axel
  - bmon
  - bzip2
  - ccze
  - curl
  - dmidecode
  - dnf-plugins-core
  - fastfetch
  - fd-find
  - fwupd
  - fzf
  - glances
  - gnupg
  - htop
  - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
  - iperf3
  - iotop
  - keepassxc
  - koji
  - libavif-tools
  - libguestfs
  - lshw
  - marked
  - mumble
  - nmap-ncat
  - p7zip
  - pavucontrol
  - pipewire-plugin-libcamera
  - kolourpaint
  - plymouth-theme-hot-dog
  - powertop
  - ripgrep
  - rsync
  - ShellCheck
  - sudo
  - sysstat
  - tmux
  - unzip
  - util-linux-user
  - vim-enhanced
  - vlc
  - virt-viewer
  - wavemon
  - xz
  - xset
  - zsh
  - zstd

dev_packages:
  - cargo
  - "@development-tools"
  - dhall
  - dhall-json
  - "g++"
  - "gcc-c++"
  - ghc
  - git
  - golang
  - golang-honnef-tools
  - krb5-devel
  - libvirt
  - nodejs
  - openssl
  - podman
  - podman-docker
  - python3-devel
  - python3-pip
  - qemu
  - virt-manager

remove_packages:
  - elisa-player
  - nano
  - akregator
  - dragon
  - pim-sieve-editor
  - mediawriter
  - kmines
  - kmail
  - kmouth
  - konversation
  - kontact
  - kf5-ktnef
  - kmahjongg

kde_packages: []
gnome_packages:
  - gnome-backgrounds-extras
  - gnome-tweaks
  - variety

pip_packages:
  - ansible-core
  - ansible-lint
  - bindep
  - black
  - bodhi-client
  - docutils
  - flake8
  - git-review
  - ipdb
  - jedi
  - jedi-language-server
  - mypy
  - neovim
  - numpy
  - mypy-extensions
  - opensearch-py
  - openstackclient
  - pandoc
  - passlib
  - pdbpp
  - pelican
  - pep8
  - pycodestyle
  - pyflakes
  - pylint
  - pynvim
  - remote_pdb
  - rstcheck
  - ruamel.yaml
  - setuptools
  - Sphinx
  - tox
  - virtualenv
  - wheel
  - yamllint
  - yapf
  - yt-dlp
  - zuulfmt

# for neovim
mason_packages:
  # - ansible-lint
  - bash-language-server
  - checkmake
  - codespell
  - commitlint
  - dhall-lsp
  - dockerfile-language-server
  - gitlint
  - goimports
  - gopls
  - helm-ls
  - html-lsp
  - jedi-language-server
  # - jinja-lsp
  - jq-lsp
  - json-lsp
  - lua-language-server
  - markdownlint
  - marksman
  - misspell
  - prettier
  - pyright
  - python-lsp-server
  - rstcheck
  - ruff
  - ruff-lsp
  - rust-analyzer
  - shellcheck
  - staticcheck
  - systemdlint
  - trivy
  - vim-language-server
  - yaml-language-server
  - yamllint
  - yamlfmt

treesitter_packages:
  - bash
  - c
  - cmake
  - comment
  - css
  - dockerfile
  - dhall
  - go
  - graphql
  - haskell
  - helm
  - html
  - http
  - lua
  - luadoc
  - javascript
  - jq
  - json
  - make
  - markdown
  - python
  - rst
  - rust
  - typescript
  - vim
  - vimdoc
  - yaml

npm_packages:
  - pnpm
  - prettier

flatpak_packages:
  # Element.io
  - im.riot.Riot
  # Signal
  - org.signal.Signal

ansible_collections:
  - community.general
  - community.crypto
  - ansible.posix
  - openstack.cloud
  - kubernetes.core
  - community.mysql
  - community.postgresql

sysctl_params:
  - name: vm.max_map_count
    value: 262144
  - name: fs.inotify.max_user_instances
    value: 8192
  - name: fs.inotify.max_user_watches
    value: 524288
