---
components: []

enable_rpmfusion: true
enable_nerd_fonts: true
enable_kubernetes_tools: true
enable_nested_virtualization: true
# small or full
nerd_fonts_pack: small
nerd_fonts_version: v2.1.0
nerd_fonts:
  - SourceCodePro
  - RobotoMono
  - DroidSansMono
  - Hack
  - FiraCode
  - FiraMono
  - Iosevka

# available: prezto, starship, oh_my_zsh
zsh_distro: oh_my_zsh

vim_distro: neovim
vim_config: coc
nvim_version: nightly

# it install nodejs into ~/.local/nodejs
nodejs_userspace: true
nodejs_version: v19.3.0

wifi_disable_powersave: true
enable_powertop: false

common_packages:
    - alacritty
    - android-file-transfer
    - axel
    - bzip2
    - ccze
    - curl
    - dnf-plugins-core
    - fd-find
    - fwupd
    - fzf
    - glances
    - gnupg
    - htop
    - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
    - iperf3
    - keepassxc
    - libavif-tools
    - lshw
    - marked
    - mumble
    - p7zip
    - pavucontrol
    - pinta
    - plymouth-theme-hot-dog
    - powertop
    - ripgrep
    - rsync
    - ShellCheck
    - sudo
    - tmux
    - unzip
    - util-linux-user
    - vim-enhanced
    - vlc
    - wavemon
    - xz
    - xset
    - zsh
    - zstd

dev_packages:
  - "@development-tools"
  - "gcc-c++"
  - ghc
  - git
  - krb5-devel
  - libvirt
  - nodejs
  - podman
  - podman-docker
  - python3-devel
  - python3-pip
  - qemu
  - virt-manager

remove_packages:
  - elisa-player
  - nano
  - akregator
  - dragon
  - pim-sieve-editor
  - mediawriter
  - kmines
  - kmail
  - kmouth
  - konversation
  - kontact
  - kf5-ktnef
  - kmahjongg

kde_packages: []
gnome_packages:
  - gnome-backgrounds-extras
  - gnome-tweaks
  - variety

pip_packages:
  - ansible==2.9.13
  - ansible-core==2.14.1
  - ansible-lint==6.11.0
  - black
  - bodhi-client
  - docutils
  - flake8
  - git-review
  - ipdb
  - jedi
  - jedi-language-server
  - mypy
  - neovim
  - numpy
  - mypy-extensions
  - opensearch-py
  - openstackclient
  - pandoc
  - pdbpp
  - pelican
  - pep8
  - pycodestyle
  - pyflakes
  - pylint
  - pynvim
  - remote_pdb
  - rstcheck
  - ruamel.yaml
  - Sphinx
  - tox
  - virtualenv
  - yamllint
  - yapf
  - yt-dlp
  - zuulfmt

npm_packages:
  - pnpm
  - prettier
